// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlcWdD605aUGvvXLSXDxsN4Mc5AcwAElI',
    appId: '1:810974274984:web:3892ad6aac98fd5b55a99d',
    messagingSenderId: '810974274984',
    projectId: 'flutter-news-app-4f0f8',
    authDomain: 'flutter-news-app-4f0f8.firebaseapp.com',
    storageBucket: 'flutter-news-app-4f0f8.appspot.com',
    measurementId: 'G-C11RJ1RKNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAq1fVI1O5ys3amaSOHZgQJ_B-ceTbBpc',
    appId: '1:810974274984:android:030319c90006e46555a99d',
    messagingSenderId: '810974274984',
    projectId: 'flutter-news-app-4f0f8',
    storageBucket: 'flutter-news-app-4f0f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1lgBJSO_NLKeVcA9DtSOgDjzMLs_tN0',
    appId: '1:810974274984:ios:cdfc51914259f47e55a99d',
    messagingSenderId: '810974274984',
    projectId: 'flutter-news-app-4f0f8',
    storageBucket: 'flutter-news-app-4f0f8.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU1lgBJSO_NLKeVcA9DtSOgDjzMLs_tN0',
    appId: '1:810974274984:ios:2b01aecd3f7d45e955a99d',
    messagingSenderId: '810974274984',
    projectId: 'flutter-news-app-4f0f8',
    storageBucket: 'flutter-news-app-4f0f8.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNewsApp.RunnerTests',
  );
}
